### ISSUE TITLE
Login Issue - Signing in with accounts that have the same email

### ISSUE THREAD

**Issue by ElSalvaDan** [DukeManh/eidetically#97]
Made a Google account and everything worked fine, then tried signing in with a GitHub account that uses that Google email and was presented with this screenshot:

![SignIn](https://user-images.githubusercontent.com/59706045/156936701-0b2919a5-0db5-4530-8bc7-bb4c469ac0d7.png)

**Comment by tpmai22** [comment]
@DukeManh Thank you Duke for fixing this
